### PR TITLE
Update from template and refactor flow

### PR DESCRIPTION
**Pull request by berziiii**
- Update from rails-template
- Migrate material from rails-api repo
- Clean up material from library-demo to be in readme.md
- Provide starter code for blog-app demo

### CODE REVIEW

**Comment by payne-chris-r** [comment]
Looks good to me. We're just using this one README now instead of rails-api. Correct?

**Comment by berziiii** [comment]
To my understanding, yes. However, you may want to add more content for each portion of single-resource(i.e. more about demo, code-along, lab domains and such). You may also find more information about things in the `rails-api-library-demo` repo and `training/single` branch. I didn't know what you wanted to bring over so just left the obvious break ups for demo, code-along and lab.

**Comment by payne-chris-r** [comment]
Cool. Thanks dude. That isn't going to happen before your lesson--I don't think. But I will do that during lunch and see if I can get it done before you start (unlikely)

**Comment by jrhorn424** [comment]
This shouldn't have anything to do with Brian's lesson. There has been a fundamental misunderstanding on one of our ends.

**Pull request closed without merging**
